/*
 * This source file was generated by the Gradle 'init' task
 */
package pariwisata;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) {
        pariwisata.database.Db.connection();
    }

    public static void main(String[] args) {
        launch(args);
    }
}